import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import Header from '@/src/components/elements/Header/Header';

import './globals.css';

export const metadata: Metadata = {
    title: {
        default: 'World Explorer | Home Page',
        template: 'World Explorer | %s',
    },
    description: 'Generated by Dmytro Rogkov',
};

type Props = {
    children: React.ReactNode;
};

const RootLayout: React.FC<Props> = ({ children }) => {
    return (
        <html lang='en' suppressHydrationWarning>
            <body>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
                    <Header />

                    <main className='relative w-full max-w-[1440px] min-h-screen p-[20px] sm:p-[24px] md:p-[40px] pt-[80px] sm:pt-[94px] md:pt-[120px] m-auto'>
                        {children}
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;
