import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import Header from '@/src/components/elements/Header/Header';

import './globals.css';

export const metadata: Metadata = {
    title: {
        default: 'World Explorer | Home Page',
        template: 'World Explorer | %s',
    },
    description: 'Generated by Dmytro Rogkov',
};

type Props = {
    children: React.ReactNode;
};

const RootLayout: React.FC<Props> = ({ children }) => {
    return (
        <html lang='en' suppressHydrationWarning>
            <body>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
                    <Header />

                    <main className='relative w-full max-w-screen-2xl min-h-screen p-5 sm:p-6 md:p-10 pt-20 sm:pt-24 md:pt-32 m-auto'>
                        {children}
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default RootLayout;
